WE:
  SpreadsheetImport:
    testing:
      domain: WE\SpreadsheetImport\Tests\Functional\Fixtures\Domain\Model\ImportTarget
      arguments:
        - { name: category, domain: 'WE\SpreadsheetImport\Tests\Functional\Fixtures\Domain\Model\ImportTargetCategory', identifier: TRUE }
        - { name: comment, static: 'Sample import' }
